export const ADD_CITY_TO_FAVORITES = 'ADD_CITY_TO_FAVORITES';
export const REMOVE_CITY_FROM_FAVORITES = 'REMOVE_CITY_FROM_FAVORITES';
export const FETCHING_FORECAST = 'FETCHING_FORECAST';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const FETCH_FAVORITES_END = 'FETCH_FAVORITES_END';