export const ADD_CITY_TO_FAVORITES = 'ADD_CITY_TO_FAVORITES';
export const REMOVE_CITY_FROM_FAVORITES = 'REMOVE_CITY_FROM_FAVORITES';
export const FETCH_FORECAST = 'FETCH_FORECAST';
export const FETCH_FAILED = 'FETCH_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';